const tap = require('tap')
const { readFileSync, writeFileSync } = require('fs')
const netlifyRedirect = require('./App')
// too lazy to build a reverse system
const v1 = readFileSync('_redirect').toString()
tap.throws(() => netlifyRedirect(), new Error('Please enter a valid url'))
tap.throws(() => netlifyRedirect(0), new Error('Please enter a valid url'))
tap.throws(() => netlifyRedirect(''), new Error('Please enter a valid url'))
tap.throws(() => netlifyRedirect('./'), new Error('Please enter a valid url'))
tap.throws(() => netlifyRedirect('http://lolcom'), new Error('Please enter a valid url'))
tap.throws(() => netlifyRedirect('http://lol.com', 'lol'), new Error('Route already exists'))
netlifyRedirect('http://lol.com', 'dummmm')
tap.equal(readFileSync('_redirect').toString().split('\n').map(l => l.split(' ')[0]).includes('/' + 'dummmm'), true)
writeFileSync('_redirect', v1)
